name: Build Veilborn Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download files
        uses: actions/checkout@v4

      - name: Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.6'

      - name: Build Mod
        working-directory: veilborn_the_island
        run: gradle build

      - name: Get JAR
        uses: actions/upload-artifact@v4
        with:
          name: Veilborn-Mod-JAR
          path: veilborn_the_island/build/libs/*.jar
